// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/app-screenshots/AICoaching.tsx": () => import("../components/mockups/app-screenshots/AICoaching.tsx"),
  "./components/mockups/app-screenshots/AIPlan.tsx": () => import("../components/mockups/app-screenshots/AIPlan.tsx"),
  "./components/mockups/app-screenshots/Achievements.tsx": () => import("../components/mockups/app-screenshots/Achievements.tsx"),
  "./components/mockups/app-screenshots/Analytics.tsx": () => import("../components/mockups/app-screenshots/Analytics.tsx"),
  "./components/mockups/app-screenshots/Dashboard.tsx": () => import("../components/mockups/app-screenshots/Dashboard.tsx"),
  "./components/mockups/app-screenshots/Goals.tsx": () => import("../components/mockups/app-screenshots/Goals.tsx"),
  "./components/mockups/app-screenshots/Journal.tsx": () => import("../components/mockups/app-screenshots/Journal.tsx"),
  "./components/mockups/app-screenshots/Paywall.tsx": () => import("../components/mockups/app-screenshots/Paywall.tsx"),
  "./components/mockups/app-screenshots/QuickTasks.tsx": () => import("../components/mockups/app-screenshots/QuickTasks.tsx"),
  "./components/mockups/dashboard-layouts/FinalDesign.tsx": () => import("../components/mockups/dashboard-layouts/FinalDesign.tsx"),
  "./components/mockups/dashboard-layouts/OptionA.tsx": () => import("../components/mockups/dashboard-layouts/OptionA.tsx"),
  "./components/mockups/dashboard-layouts/OptionB.tsx": () => import("../components/mockups/dashboard-layouts/OptionB.tsx"),
  "./components/mockups/dashboard-layouts/RevampedDashboard.tsx": () => import("../components/mockups/dashboard-layouts/RevampedDashboard.tsx")
};
