// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-layouts/OptionA.tsx": () => import("../components/mockups/dashboard-layouts/OptionA.tsx"),
  "./components/mockups/dashboard-layouts/OptionB.tsx": () => import("../components/mockups/dashboard-layouts/OptionB.tsx")
};
