import { useState, useEffect } from "react";
import { useMutation } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ScrollArea } from "@/components/ui/scroll-area";
import { 
  Lightbulb, 
  BookOpen, 
  Wrench, 
  Video, 
  FileText, 
  ExternalLink, 
  Loader2,
  Sparkles,
  CheckCircle,
  AlertCircle,
  Smartphone,
  Globe,
  BookMarked,
  ClipboardList,
  Download,
  Play,
  Star,
  ArrowRight
} from "lucide-react";
import { cn } from "@/lib/utils";
import type { RoutineTask } from "@shared/schema";
import { jsPDF } from "jspdf";

interface VideoSuggestion {
  title: string;
  searchQuery: string;
  videoId?: string;
  channel?: string;
  duration?: string;
}

interface ToolResource {
  id: string;
  name: string;
  type: string;
  description: string;
  url?: string;
  features?: string[];
  pricing?: string;
}

interface Template {
  title: string;
  content: string;
  format: string;
}

interface GuidanceData {
  examples: string[];
  tips: string[];
  tools: ToolResource[];
  templates: Template[];
  videos: VideoSuggestion[];
}

interface TaskGuidanceModalProps {
  habitId: number;
  task: RoutineTask;
  habitTitle: string;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

const resourceIcons: Record<string, React.ReactNode> = {
  app: <Smartphone className="w-4 h-4" />,
  website: <Globe className="w-4 h-4" />,
  tool: <Wrench className="w-4 h-4" />,
  book: <BookMarked className="w-4 h-4" />,
  template: <ClipboardList className="w-4 h-4" />,
  video: <Video className="w-4 h-4" />,
  software: <Globe className="w-4 h-4" />,
  service: <Star className="w-4 h-4" />,
};

export function TaskGuidanceModal({ habitId, task, habitTitle, open, onOpenChange }: TaskGuidanceModalProps) {
  const [guidance, setGuidance] = useState<GuidanceData | null>(null);
  const [activeTab, setActiveTab] = useState("examples");

  const guidanceMutation = useMutation({
    mutationFn: async () => {
      const res = await apiRequest("POST", `/api/habits/${habitId}/tasks/${task.id}/guidance`, {
        taskTitle: task.title,
        taskDescription: task.description,
        habitTitle: habitTitle,
      });
      return res.json();
    },
    onSuccess: (data) => {
      setGuidance(data);
    },
  });

  useEffect(() => {
    if (open && !guidance && !guidanceMutation.isPending) {
      guidanceMutation.mutate();
    }
  }, [open, guidance, guidanceMutation.isPending]);

  useEffect(() => {
    setGuidance(null);
    setActiveTab("examples");
  }, [task.id]);

  const handleVideoClick = (video: VideoSuggestion) => {
    if (video.videoId) {
      window.open(`https://www.youtube.com/watch?v=${video.videoId}`, '_blank', 'noopener,noreferrer');
    } else {
      window.open(`https://www.youtube.com/results?search_query=${encodeURIComponent(video.searchQuery)}`, '_blank', 'noopener,noreferrer');
    }
  };

  const downloadTemplate = (template: Template) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxWidth = pageWidth - (margin * 2);
    
    // Title
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text(template.title, margin, 25);
    
    // Subtitle
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    doc.text(`For: ${habitTitle} - ${task.title}`, margin, 33);
    doc.text(`Generated by HabitGrow`, margin, 39);
    
    // Line separator
    doc.setDrawColor(200);
    doc.line(margin, 45, pageWidth - margin, 45);
    
    // Content
    doc.setFontSize(11);
    doc.setTextColor(0);
    const lines = doc.splitTextToSize(template.content, maxWidth);
    let yPos = 55;
    
    lines.forEach((line: string) => {
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }
      doc.text(line, margin, yPos);
      yPos += 6;
    });
    
    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text("Created with HabitGrow - Your AI Habit Coach", margin, 285);
    
    doc.save(`${template.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf`);
  };

  const copyTemplate = (template: Template) => {
    navigator.clipboard.writeText(template.content);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-3xl max-h-[90vh] flex flex-col">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center">
              <Sparkles className="w-4 h-4 text-primary" />
            </div>
            <div className="flex flex-col">
              <span>Smart Guidance & Resources</span>
              <span className="text-sm font-normal text-muted-foreground truncate max-w-[400px]">
                {task.title}
              </span>
            </div>
          </DialogTitle>
        </DialogHeader>

        {(guidanceMutation.isPending || (!guidance && !guidanceMutation.isError)) ? (
          <div className="flex flex-col items-center justify-center py-16 space-y-4">
            <div className="w-20 h-20 rounded-full bg-gradient-to-br from-primary/20 to-primary/5 flex items-center justify-center">
              <Loader2 className="w-10 h-10 text-primary animate-spin" />
            </div>
            <div className="text-center space-y-2">
              <h3 className="font-semibold text-lg">Your AI Coach is Working</h3>
              <p className="text-sm text-muted-foreground max-w-sm">
                Finding real videos, apps, templates, and expert advice for your task...
              </p>
            </div>
          </div>
        ) : guidanceMutation.isError ? (
          <div className="flex flex-col items-center justify-center py-16 space-y-4">
            <div className="w-20 h-20 rounded-full bg-destructive/10 flex items-center justify-center">
              <AlertCircle className="w-10 h-10 text-destructive" />
            </div>
            <div className="text-center space-y-2">
              <h3 className="font-semibold text-lg">Couldn't Load Resources</h3>
              <p className="text-sm text-muted-foreground">
                There was a problem getting guidance. Please try again.
              </p>
            </div>
            <Button onClick={() => guidanceMutation.mutate()} data-testid="button-retry-guidance">
              Try Again
            </Button>
          </div>
        ) : guidance ? (
          <ScrollArea className="flex-1 -mx-6 px-6">
            <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
              <TabsList className="grid w-full grid-cols-5 mb-4">
                <TabsTrigger value="examples" className="gap-1.5 text-xs sm:text-sm" data-testid="tab-examples">
                  <Lightbulb className="w-3.5 h-3.5" />
                  <span className="hidden sm:inline">Examples</span>
                </TabsTrigger>
                <TabsTrigger value="tips" className="gap-1.5 text-xs sm:text-sm" data-testid="tab-tips">
                  <CheckCircle className="w-3.5 h-3.5" />
                  <span className="hidden sm:inline">Tips</span>
                </TabsTrigger>
                <TabsTrigger value="tools" className="gap-1.5 text-xs sm:text-sm" data-testid="tab-tools">
                  <Wrench className="w-3.5 h-3.5" />
                  <span className="hidden sm:inline">Tools</span>
                </TabsTrigger>
                <TabsTrigger value="templates" className="gap-1.5 text-xs sm:text-sm" data-testid="tab-templates">
                  <FileText className="w-3.5 h-3.5" />
                  <span className="hidden sm:inline">Templates</span>
                </TabsTrigger>
                <TabsTrigger value="videos" className="gap-1.5 text-xs sm:text-sm" data-testid="tab-videos">
                  <Video className="w-3.5 h-3.5" />
                  <span className="hidden sm:inline">Videos</span>
                </TabsTrigger>
              </TabsList>

              <TabsContent value="examples" className="space-y-4 mt-0">
                <div className="bg-primary/5 rounded-lg p-4 border border-primary/10">
                  <p className="text-sm font-medium flex items-center gap-2">
                    <Star className="w-4 h-4 text-primary" />
                    Step-by-step examples showing exactly how to do this
                  </p>
                </div>
                {guidance.examples?.map((example, index) => (
                  <Card key={index} className="bg-primary/5" data-testid={`card-example-${index}`}>
                    <CardContent className="p-4">
                      <div className="flex gap-4">
                        <div className="w-8 h-8 rounded-full bg-primary flex items-center justify-center flex-shrink-0">
                          <span className="text-sm font-bold text-primary-foreground">{index + 1}</span>
                        </div>
                        <div className="flex-1">
                          <p className="text-sm whitespace-pre-wrap leading-relaxed" data-testid={`text-example-${index}`}>{example}</p>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </TabsContent>

              <TabsContent value="tips" className="space-y-4 mt-0">
                <div className="bg-green-500/5 rounded-lg p-4 border border-green-500/10">
                  <p className="text-sm font-medium flex items-center gap-2">
                    <CheckCircle className="w-4 h-4 text-green-500" />
                    Expert coaching tips to maximize your success
                  </p>
                </div>
                {guidance.tips?.map((tip, index) => (
                  <Card key={index} className="bg-gradient-to-r from-green-500/5 to-transparent" data-testid={`card-tip-${index}`}>
                    <CardContent className="p-4">
                      <div className="flex gap-3">
                        <div className="w-6 h-6 rounded-full bg-green-500/20 flex items-center justify-center flex-shrink-0">
                          <CheckCircle className="w-4 h-4 text-green-600" />
                        </div>
                        <p className="text-sm leading-relaxed" data-testid={`text-tip-${index}`}>{tip}</p>
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </TabsContent>

              <TabsContent value="tools" className="space-y-4 mt-0">
                <div className="bg-blue-500/5 rounded-lg p-4 border border-blue-500/10">
                  <p className="text-sm font-medium flex items-center gap-2">
                    <Wrench className="w-4 h-4 text-blue-500" />
                    Recommended apps, websites, and tools to help you
                  </p>
                </div>
                <div className="grid gap-4">
                  {guidance.tools?.map((tool, index) => (
                    <Card key={index} className="hover-elevate overflow-visible" data-testid={`card-tool-${index}`}>
                      <CardContent className="p-4">
                        <div className="flex items-start gap-4">
                          <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-blue-500/20 to-purple-500/20 flex items-center justify-center flex-shrink-0">
                            {resourceIcons[tool.type] || <Globe className="w-6 h-6 text-blue-500" />}
                          </div>
                          <div className="flex-1 min-w-0">
                            <div className="flex items-center gap-2 flex-wrap">
                              <h4 className="font-semibold" data-testid={`text-tool-name-${index}`}>{tool.name}</h4>
                              <Badge variant="secondary" className="text-xs capitalize">
                                {tool.type}
                              </Badge>
                              {tool.pricing && (
                                <Badge variant="outline" className="text-xs">
                                  {tool.pricing}
                                </Badge>
                              )}
                            </div>
                            <p className="text-sm text-muted-foreground mt-1.5">
                              {tool.description}
                            </p>
                            {tool.features && tool.features.length > 0 && (
                              <div className="flex flex-wrap gap-1.5 mt-2">
                                {tool.features.map((feature, i) => (
                                  <Badge key={i} variant="outline" className="text-xs font-normal">
                                    {feature}
                                  </Badge>
                                ))}
                              </div>
                            )}
                            {tool.url && (
                              <a 
                                href={tool.url} 
                                target="_blank" 
                                rel="noopener noreferrer"
                                className="inline-flex items-center text-sm text-primary hover:underline mt-2"
                                data-testid={`link-tool-${index}`}
                              >
                                Visit Website <ExternalLink className="w-3 h-3 ml-1" />
                              </a>
                            )}
                          </div>
                        </div>
                      </CardContent>
                    </Card>
                  ))}
                </div>
              </TabsContent>

              <TabsContent value="templates" className="space-y-4 mt-0">
                <div className="bg-purple-500/5 rounded-lg p-4 border border-purple-500/10">
                  <p className="text-sm font-medium flex items-center gap-2">
                    <FileText className="w-4 h-4 text-purple-500" />
                    Downloadable templates and checklists ready to use
                  </p>
                </div>
                {guidance.templates?.map((template, index) => (
                  <Card key={index} className="overflow-hidden" data-testid={`card-template-${index}`}>
                    <CardHeader className="pb-2 bg-muted/30">
                      <div className="flex items-center justify-between">
                        <CardTitle className="text-base flex items-center gap-2" data-testid={`text-template-title-${index}`}>
                          <FileText className="w-5 h-5 text-purple-500" />
                          {template.title}
                        </CardTitle>
                        <div className="flex gap-2">
                          <Button 
                            size="sm" 
                            variant="outline"
                            onClick={() => copyTemplate(template)}
                            data-testid={`button-copy-template-${index}`}
                          >
                            <ClipboardList className="w-4 h-4 mr-1" />
                            Copy
                          </Button>
                          <Button 
                            size="sm"
                            onClick={() => downloadTemplate(template)}
                            data-testid={`button-download-template-${index}`}
                          >
                            <Download className="w-4 h-4 mr-1" />
                            Download PDF
                          </Button>
                        </div>
                      </div>
                    </CardHeader>
                    <CardContent className="pt-4">
                      <pre className="text-sm whitespace-pre-wrap font-mono bg-muted/50 p-4 rounded-lg border overflow-x-auto max-h-60">
                        {template.content}
                      </pre>
                    </CardContent>
                  </Card>
                ))}
              </TabsContent>

              <TabsContent value="videos" className="space-y-4 mt-0">
                <div className="bg-red-500/5 rounded-lg p-4 border border-red-500/10">
                  <p className="text-sm font-medium flex items-center gap-2">
                    <Video className="w-4 h-4 text-red-500" />
                    Video tutorials to guide you step by step
                  </p>
                </div>
                <div className="grid gap-4 sm:grid-cols-2">
                  {guidance.videos?.map((video, index) => (
                    <Card 
                      key={index} 
                      className="hover-elevate cursor-pointer overflow-hidden group"
                      onClick={() => handleVideoClick(video)}
                      data-testid={`card-video-${index}`}
                    >
                      <div className="relative aspect-video bg-gradient-to-br from-red-500/20 to-red-600/30 flex items-center justify-center">
                        {video.videoId ? (
                          <img 
                            src={`https://img.youtube.com/vi/${video.videoId}/mqdefault.jpg`}
                            alt={video.title}
                            className="w-full h-full object-cover"
                          />
                        ) : null}
                        <div className="absolute inset-0 flex items-center justify-center bg-black/30 group-hover:bg-black/40 transition-colors">
                          <div className="w-16 h-16 rounded-full bg-red-600 flex items-center justify-center shadow-lg group-hover:scale-110 transition-transform">
                            <Play className="w-8 h-8 text-white ml-1" />
                          </div>
                        </div>
                        {video.duration && (
                          <Badge className="absolute bottom-2 right-2 bg-black/80">
                            {video.duration}
                          </Badge>
                        )}
                      </div>
                      <CardContent className="p-3">
                        <h4 className="font-medium text-sm line-clamp-2">{video.title}</h4>
                        {video.channel && (
                          <p className="text-xs text-muted-foreground mt-1">{video.channel}</p>
                        )}
                      </CardContent>
                    </Card>
                  ))}
                </div>
              </TabsContent>
            </Tabs>
          </ScrollArea>
        ) : null}
      </DialogContent>
    </Dialog>
  );
}
